In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv(r"C:\Users\varun\OneDrive\Desktop\DISCOUNT_RECOMMENDATION_SYSTEM\Data\customer_data.csv")

In [4]:
df.head(5)

,Age,Gender,Marital Status,Occupation,Educational Qualifications,Family size,Frequently used Medium,Frequently ordered Meal category,Perference,Restaurnat Rating,...,Order Value,Ease and convenient,Self Cooking,Health Concern,Late Delivery,Poor Hygiene,Bad past experience,More Offers and Discount,Maximum wait time,Influence of rating
0,20,Female,Single,Student,Post Graduate,4,Food delivery apps,Breakfast,Non Veg foods (Lunch / Dinner),1,...,1,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,30 minutes,Yes
1,24,Female,Single,Student,Graduate,3,Food delivery apps,Snacks,Non Veg foods (Lunch / Dinner),1,...,3,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly agree,30 minutes,Yes
2,22,Male,Single,Student,Post Graduate,3,Food delivery apps,Lunch,Non Veg foods (Lunch / Dinner),3,...,1,Strongly agree,Disagree,Neutral,Neutral,Agree,Agree,Neutral,45 minutes,Yes
3,22,Female,Single,Student,Graduate,6,Food delivery apps,Snacks,Veg foods (Breakfast / Lunch / Dinner),2,...,1,Agree,Agree,Strongly agree,Neutral,Agree,Disagree,Strongly agree,30 minutes,Yes
4,22,Male,Single,Student,Post Graduate,4,Walk-in,Lunch,Non Veg foods (Lunch / Dinner),3,...,3,Agree,Agree,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,30 minutes,Yes

In [5]:
df.shape

(499, 23)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                499 non-null    int64
 1   Gender                             498 non-null    str
 2   Marital Status                     499 non-null    str
 3   Occupation                         498 non-null    str
 4   Educational Qualifications         499 non-null    str
 5   Family size                        499 non-null    int64
 6   Frequently used Medium             498 non-null    str
 7   Frequently ordered Meal category   498 non-null    str
 8   Perference                         498 non-null    str
 9   Restaurnat Rating                  499 non-null    int64
 10  Delivery Rating                    499 non-null    int64
 11  No. of orders placed               499 non-null    int64
 12  Delivery Time                      498 non-null    str
 13  Order Value                        499 non-null    int64
 14  Ease and convenient                498 non-null    str
 15  Self Cooking                       499 non-null    str
 16  Health Concern                     498 non-null    str
 17  Late Delivery                      499 non-null    str
 18  Poor Hygiene                       499 non-null    str
 19  Bad past experience                498 non-null    str
 20  More Offers and Discount           498 non-null    str
 21  Maximum wait time                  497 non-null    str
 22  Influence of rating                499 non-null    str
dtypes: int64(6), str(17)
memory usage: 89.8 KB

In [7]:
final_cols = [
    'Age',
    'Occupation',
    'Family size',
    'Frequently used Medium',
    'Frequently ordered Meal category ',
    'Perference',
    'Restaurnat Rating',
    'Delivery Rating',
    'Order Value',
    'No. of orders placed',
    'Maximum wait time',
    'More Offers and Discount',
    'Influence of rating',
    'Ease and convenient',
    'Late Delivery',
    'Bad past experience'
]

df_model = df[final_cols]

In [8]:
df_model.head(5)

,Age,Occupation,Family size,Frequently used Medium,Frequently ordered Meal category,Perference,Restaurnat Rating,Delivery Rating,Order Value,No. of orders placed,Maximum wait time,More Offers and Discount,Influence of rating,Ease and convenient,Late Delivery,Bad past experience
0,20,Student,4,Food delivery apps,Breakfast,Non Veg foods (Lunch / Dinner),1,1,1,150,30 minutes,Neutral,Yes,Neutral,Neutral,Neutral
1,24,Student,3,Food delivery apps,Snacks,Non Veg foods (Lunch / Dinner),1,1,3,32,30 minutes,Strongly agree,Yes,Strongly agree,Agree,Strongly agree
2,22,Student,3,Food delivery apps,Lunch,Non Veg foods (Lunch / Dinner),3,5,1,193,45 minutes,Neutral,Yes,Strongly agree,Neutral,Agree
3,22,Student,6,Food delivery apps,Snacks,Veg foods (Breakfast / Lunch / Dinner),2,4,1,60,30 minutes,Strongly agree,Yes,Agree,Neutral,Disagree
4,22,Student,4,Walk-in,Lunch,Non Veg foods (Lunch / Dinner),3,1,3,234,30 minutes,Agree,Yes,Agree,Strongly agree,Strongly agree

In [9]:
df_model.isnull().sum()

Age                                  0
Occupation                           1
Family size                          0
Frequently used Medium               1
Frequently ordered Meal category     1
Perference                           1
Restaurnat Rating                    0
Delivery Rating                      0
Order Value                          0
No. of orders placed                 0
Maximum wait time                    2
More Offers and Discount             1
Influence of rating                  0
Ease and convenient                  1
Late Delivery                        0
Bad past experience                  1
dtype: int64

In [10]:
num_cols = df_model.select_dtypes(include=['int64','float64']).columns
df_model[num_cols]= df_model[num_cols].fillna(df_model[num_cols].median())

In [11]:
cat_cols = df_model.select_dtypes(include=['object']).columns
for col in cat_cols:
    df_model[col]=df_model[col].fillna(df_model[col].mode()[0])

In [12]:
df_model.isnull().sum()

Age                                  0
Occupation                           0
Family size                          0
Frequently used Medium               0
Frequently ordered Meal category     0
Perference                           0
Restaurnat Rating                    0
Delivery Rating                      0
Order Value                          0
No. of orders placed                 0
Maximum wait time                    0
More Offers and Discount             0
Influence of rating                  0
Ease and convenient                  0
Late Delivery                        0
Bad past experience                  0
dtype: int64

## ENCODING ALL CATEGORICAL VARIABLES
strongly disagree < disagree < neutral < agree < strongly agree

In [13]:
df_model = df_model.copy()

In [14]:
ordinal_cols = [
    'Ease and convenient',
    'Late Delivery',
    'Bad past experience',
    'More Offers and Discount'
]

binary_cols = ['Influence of rating']

for col in ordinal_cols + binary_cols:
    df_model[col] = (
        df_model[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

In [15]:
ordinal_map = {
    'strongly disagree': 1,
    'disagree': 2,
    'neutral': 3,
    'agree': 4,
    'strongly agree': 5
}


binary_map = {
    'yes': 1,
    'no': 0
}

In [16]:
# Ordinal encoding
for col in ordinal_cols:
    df_model[col] = df_model[col].map(ordinal_map)

# Binary encoding
df_model['Influence of rating'] = df_model['Influence of rating'].map(binary_map)

In [17]:
# Fill ordinal with median
for col in ordinal_cols:
    df_model[col] = df_model[col].fillna(df_model[col].median())

# Fill binary with mode
df_model['Influence of rating'] = df_model['Influence of rating'].fillna(
    df_model['Influence of rating'].mode()[0]
)

In [18]:
df_model[ordinal_cols + binary_cols].isnull().sum()

Ease and convenient         0
Late Delivery               0
Bad past experience         0
More Offers and Discount    0
Influence of rating         0
dtype: int64

In [19]:
df_model.head(5)

,Age,Occupation,Family size,Frequently used Medium,Frequently ordered Meal category,Perference,Restaurnat Rating,Delivery Rating,Order Value,No. of orders placed,Maximum wait time,More Offers and Discount,Influence of rating,Ease and convenient,Late Delivery,Bad past experience
0,20,Student,4,Food delivery apps,Breakfast,Non Veg foods (Lunch / Dinner),1,1,1,150,30 minutes,3,1.0,3,3,3
1,24,Student,3,Food delivery apps,Snacks,Non Veg foods (Lunch / Dinner),1,1,3,32,30 minutes,5,1.0,5,4,5
2,22,Student,3,Food delivery apps,Lunch,Non Veg foods (Lunch / Dinner),3,5,1,193,45 minutes,3,1.0,5,3,4
3,22,Student,6,Food delivery apps,Snacks,Veg foods (Breakfast / Lunch / Dinner),2,4,1,60,30 minutes,5,1.0,4,3,2
4,22,Student,4,Walk-in,Lunch,Non Veg foods (Lunch / Dinner),3,1,3,234,30 minutes,4,1.0,4,5,5

In [20]:
nominal_cols = [
    'Occupation',
    'Frequently used Medium',
    'Frequently ordered Meal category ',
    'Perference'
]

df_model = pd.get_dummies(
    df_model,
    columns=nominal_cols,
    drop_first=True
)

In [21]:
df_model.head(5)

,Age,Family size,Restaurnat Rating,Delivery Rating,Order Value,No. of orders placed,Maximum wait time,More Offers and Discount,Influence of rating,Ease and convenient,...,Occupation_Student,Frequently used Medium_Food delivery apps,Frequently used Medium_Walk-in,Frequently used Medium_Web browser,Frequently ordered Meal category _Dinner,Frequently ordered Meal category _Lunch,Frequently ordered Meal category _Snacks,Perference_Non Veg foods (Lunch / Dinner),Perference_Sweets,Perference_Veg foods (Breakfast / Lunch / Dinner)
0,20,4,1,1,1,150,30 minutes,3,1.0,3,...,True,True,False,False,False,False,False,True,False,False
1,24,3,1,1,3,32,30 minutes,5,1.0,5,...,True,True,False,False,False,False,True,True,False,False
2,22,3,3,5,1,193,45 minutes,3,1.0,5,...,True,True,False,False,False,True,False,True,False,False
3,22,6,2,4,1,60,30 minutes,5,1.0,4,...,True,True,False,False,False,False,True,False,False,True
4,22,4,3,1,3,234,30 minutes,4,1.0,4,...,True,False,True,False,False,True,False,True,False,False

In [22]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 24 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Age                                                499 non-null    int64
 1   Family size                                        499 non-null    int64
 2   Restaurnat Rating                                  499 non-null    int64
 3   Delivery Rating                                    499 non-null    int64
 4   Order Value                                        499 non-null    int64
 5   No. of orders placed                               499 non-null    int64
 6   Maximum wait time                                  499 non-null    str
 7   More Offers and Discount                           499 non-null    int64
 8   Influence of rating                                499 non-null    float64
 9   Ease and convenient                                499 non-null    int64
 10  Late Delivery                                      499 non-null    int64
 11  Bad past experience                                499 non-null    int64
 12  Occupation_House wife                              499 non-null    bool
 13  Occupation_Self Employeed                          499 non-null    bool
 14  Occupation_Student                                 499 non-null    bool
 15  Frequently used Medium_Food delivery apps          499 non-null    bool
 16  Frequently used Medium_Walk-in                     499 non-null    bool
 17  Frequently used Medium_Web browser                 499 non-null    bool
 18  Frequently ordered Meal category _Dinner           499 non-null    bool
 19  Frequently ordered Meal category _Lunch            499 non-null    bool
 20  Frequently ordered Meal category _Snacks           499 non-null    bool
 21  Perference_Non Veg foods (Lunch / Dinner)          499 non-null    bool
 22  Perference_Sweets                                  499 non-null    bool
 23  Perference_Veg foods (Breakfast / Lunch / Dinner)  499 non-null    bool
dtypes: bool(12), float64(1), int64(10), str(1)
memory usage: 52.8 KB

## Combining two columns to create target column for our model

In [23]:
## (column1) discount sensitive columns 
df_model['is_discount_sensitive'] = (df_model['More Offers and Discount'] >= 4).astype(int)

##(column2) frequency of orders without discounts
high_order_threshold = df_model['No. of orders placed'].quantile(0.7)

df_model['is_high_order'] = (df_model['No. of orders placed'] >= high_order_threshold).astype(int)

In [24]:
df_model['target_disocunt_growth']= (
(df_model['is_discount_sensitive']==1) & 
(df_model['is_high_order']==0)).astype(int)

In [25]:
df_model['target_disocunt_growth'].value_counts()

target_disocunt_growth
0    293
1    206
Name: count, dtype: int64

## Now split dependent and independent variables

In [26]:
target = 'target_disocunt_growth'

In [27]:
y = df_model[target]

X = df_model.drop(columns=[
    'target_disocunt_growth',   
    'More Offers and Discount', 
    'No. of orders placed',     
    'is_discount_sensitive',    
    'is_high_order'             
])

In [29]:
df_model.to_csv("Data\processed_data.csv", index=False)